//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public Nullable<int> ArticleCategoryId { get; set; }
        public string BigImage { get; set; }
        public string SmallImage { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleContent { get; set; }
        public bool IsHot { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual ArticleCategory ArticleCategory { get; set; }
    }
}
