//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowInfo_InvestRecord
    {
        public System.Guid Id { get; set; }
        public int BorrowInfoId { get; set; }
        public System.Guid UserId { get; set; }
        public double Amount { get; set; }
        public double Yield { get; set; }
        public double Fee { get; set; }
        public double Profit { get; set; }
        public double ActualProfit { get; set; }
        public double Income { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public Nullable<System.DateTime> InvestStartDate { get; set; }
        public Nullable<System.DateTime> InvestEndDate { get; set; }
        public byte Status { get; set; }
        public string Remark { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SSN { get; set; }
    
        public virtual BorrowInfo BorrowInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
