//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLog
    {
        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string ActionName { get; set; }
        public string ActionDesc { get; set; }
        public System.DateTime ActionDate { get; set; }
    }
}
