//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_b_repayinfo
    {
        public System.Guid brokeruserid { get; set; }
        public decimal repayamount { get; set; }
        public decimal outcash { get; set; }
        public System.DateTime createtime { get; set; }
        public System.DateTime modifytime { get; set; }
        public decimal freezeamount { get; set; }
    }
}
