//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_code
    {
        public int code_id { get; set; }
        public string code_sort_type { get; set; }
        public byte value { get; set; }
        public string name { get; set; }
        public Nullable<byte> disp_no { get; set; }
        public string org_no { get; set; }
        public Nullable<byte> p_code { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string comment4 { get; set; }
        public string comment5 { get; set; }
    }
}
