//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_p_apierrcode
    {
        public int apierrcodeid { get; set; }
        public int apierrcodekey { get; set; }
        public string apierrcodevalue { get; set; }
        public string comment { get; set; }
        public System.DateTime createtime { get; set; }
        public System.DateTime modifytime { get; set; }
    }
}
