//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayMehod
    {
        public PayMehod()
        {
            this.BorrowInfo = new HashSet<BorrowInfo>();
        }
    
        public int Id { get; set; }
        public string PayMethodName { get; set; }
    
        public virtual ICollection<BorrowInfo> BorrowInfo { get; set; }
    }
}
