//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreGet
    {
        public ScoreGet()
        {
            this.UserInfo_Score = new HashSet<UserInfo_Score>();
        }
    
        public int ScoreType { get; set; }
        public string ScoreDesc { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ICollection<UserInfo_Score> UserInfo_Score { get; set; }
    }
}
