//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.BorrowInfo_InvestRecord = new HashSet<BorrowInfo_InvestRecord>();
            this.UserInfo_BankCard = new HashSet<UserInfo_BankCard>();
            this.UserInfo_Invest = new HashSet<UserInfo_Invest>();
            this.UserInfo_Score = new HashSet<UserInfo_Score>();
            this.UserLog = new HashSet<UserLog>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string FullName { get; set; }
        public string IDNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public byte UserStatus { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<System.DateTime> PreLoginDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public byte FailedLoginCount { get; set; }
        public byte UserLevel { get; set; }
        public bool FuiouValid { get; set; }
        public string InviteCode { get; set; }
        public string InvitedUserCode { get; set; }
        public string HeadImg { get; set; }
        public Nullable<System.DateTime> LoginFaileDate { get; set; }
        public Nullable<System.DateTime> PreviousLoginDate { get; set; }
        public Nullable<double> UserScore { get; set; }
    
        public virtual ICollection<BorrowInfo_InvestRecord> BorrowInfo_InvestRecord { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual ICollection<UserInfo_BankCard> UserInfo_BankCard { get; set; }
        public virtual ICollection<UserInfo_Invest> UserInfo_Invest { get; set; }
        public virtual ICollection<UserInfo_Score> UserInfo_Score { get; set; }
        public virtual ICollection<UserLog> UserLog { get; set; }
    }
}
