//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo_BankCard
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<int> BankProvinceId { get; set; }
        public Nullable<int> BankCityId { get; set; }
        public Nullable<int> BankAreaId { get; set; }
        public string BankAddress { get; set; }
        public string BankName { get; set; }
        public string BankCardNo { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
